/* definitions generated by preprocessor, copy into defines.h */

#ifndef	PPINC
//#define	_ATMEGA2560	// device select: _ATMEGAxxxx
#define	_B2048	// boot size select: _Bxxxx (words), powers of two only



//#define _ATTINY25  //  added for Slave device selection

//#define _ATMEGA48   //  added for Slave device selection
//#define _ATTINY85   //  added for Slave device selection

#define _ATTINY88   //added for Slave device selection


/* define pin for enter-self-prog-mode */
#define	PROGPORT	PORTD
#define	PROGPIN	PIND
#define	PROG_NO	PD4

/* baud rate register value calculation */
#define	CPU_FREQ	3690000
#define	BAUD_RATE	115200
#define	BRREG_VALUE	1

/* definitions for UART control */
#define	BAUD_RATE_LOW_REG	UBRR0L
#define	UART_CONTROL_REG	UCSR0B
#define	ENABLE_TRANSMITTER_BIT	TXEN0
#define	ENABLE_RECEIVER_BIT	RXEN0
#define	UART_STATUS_REG	UCSR0A
#define	TRANSMIT_COMPLETE_BIT	TXC0
#define	RECEIVE_COMPLETE_BIT	RXC0
#define	UART_DATA_REG	UDR0

/* definitions for SPM control */
#define	SPMCR_REG	SPMCSR
#define	PAGESIZE	256
#define	APP_END	258048
#define	LARGE_MEMORY

/* definitions for device recognition */
#define	PARTCODE	0
#define	SIGNATURE_BYTE_1	0x1E
#define	SIGNATURE_BYTE_2	0x98
#define	SIGNATURE_BYTE_3	0x01

/* indicate that preprocessor result is included */
#define	PPINC
#endif
